// server/engines/places/schema.js

export const defaultPlaceSchema = {
  engineKey: "places",
  projectName: "City Places",
  projectDescription: "",
  projectTags: [],
  ownerColorTheme: "green",
  previewText: "sections[0].inputs[0].value", // Location Name
  geometry: {
    label: "Geometry",
      types: [
    "Point",
    "LineString",
    "Polygon",
  ],
    isFilter: true,
    isDisplayed: true,
  },

  time: {
    label: "Timezone",
    type: "None",
    isFilter: false,
    isDisplayed: false,
  },

  sections: [
    // ─────────────────────────────────────────────
    // Location
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 10,
      name: "Location",
      systemKey: "location",
      inputs: [
        {
          id: Date.now() + 11,
          label: "Location Name",
          type: "text",
          isRequired: true,
          isFilter: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
        {
          id: Date.now() + 12,
          label: "Address",
          type: "text",
          isRequired: false,
          isFilter: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Details
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 20,
      name: "Details",
      inputs: [
        {
          id: Date.now() + 21,
          label: "Description",
          type: "notes",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 1000,
        },
        {
          id: Date.now() + 22,
          label: "Category",
          type: "tagList",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
          maxItems: 1000,
          allowCustomTags: true,
          customTags: [],
          defaultTags: [],
        },
        {
          id: Date.now() + 23,
          label: "Space Uses",
          type: "tagList",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
          maxItems: 1000,
          allowCustomTags: true,
          customTags: [],
          defaultTags: [],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Contact Details
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 30,
      name: "Contact Details",
      systemKey: "contact",
      inputs: [
        {
          id: Date.now() + 31,
          label: "Website",
          type: "website",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
        {
          id: Date.now() + 32,
          label: "Phone",
          type: "phoneNumber",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 25,
        },
        {
          id: Date.now() + 33,
          label: "Extension",
          type: "text",
          isRequired: false,
          isFilter: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 20,
        },
        {
          id: Date.now() + 34,
          label: "Email",
          type: "email",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Capacity
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 40,
      name: "Capacity",
      systemKey: "capacity",
      inputs: [
        {
          id: Date.now() + 41,
          label: "Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value", "Min-Max Range"],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Access Conditions
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 50,
      name: "Access Conditions",
      inputs: [
        {
          id: Date.now() + 51,
          label: "Indoor/Outdoor",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: ["Indoor", "Outdoor", "Both"],
        },
        {
          id: Date.now() + 52,
          label: "Noise Level",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: ["Low", "Medium", "High"],
        },
        {
          id: Date.now() + 53,
          label: "Pet Friendly",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: ["Pets Allowed", "Service Animals Only", "No Pets Allowed"],
        },
        {
          id: Date.now() + 54,
          label: "Access Type",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: [
            "Public Access",
            "Request Access",
            "Staff Escort Required",
            "Appointment Required",
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Time Access
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 60,
      name: "Time Access",
      systemKey: "timeAccess",
      conditionalSection: "checkboxGate",

      checkboxGateConfig: {
        primaryInputKeys: ["hoursKnown"],
        secondaryInputMap: {
          hoursKnown: ["hours"],
        },
      },

      inputs: [
        {
          id: Date.now() + 61,
          label: "Hours Known?",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "Hours unknown",
          notes: "",
          isApplicableOption: false,
          inputKey: "hoursKnown",
          secondaryFor: null,
        },
        {
          id: Date.now() + 62,
          label: "Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: true,
          inputKey: "hours",
          secondaryFor: "hoursKnown",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Financial Access
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 70,
      name: "Financial Access",
      systemKey: "financialAccess",
      inputs: [
        {
          id: Date.now() + 71,
          label: "Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "100000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: [
            "Entry Fee",
            "Rental Fee",
            "Ticket",
            "Donation",
            "Item",
            "Service",
            "Food",
            "Merch",
            "Exercise Class",
            "Photography",
            "Membership",
          ],
          customCategoryOptions: [],
          priceModeOptions: [
            "Free",
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            "Entry Fee": ["One-time", "Per Person", "Per Group"],
            "Rental Fee": ["One-time", "Per Person", "Per Group", "Per Hour"],
            Ticket: ["Per Person", "Per Group"],
            Donation: ["One-time", "Per Person"],
            Item: ["Per Item"],
            Service: ["Per Hour", "Per Session", "One-time"],
            Food: ["Per Item"],
            Merch: ["Per Item"],
            "Exercise Class": ["Per Class"],
            Photography: ["Per Session", "Per Hour"],
            Membership: ["Per Month", "Per Year"],
          },
          customUnitOptionsByCategory: {},
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Parking
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 80,
      name: "Parking",
      systemKey: "parking",
      conditionalSection: "checkboxGate",
      checkboxGateConfig: {
        primaryInputKeys: [
          "freeLotGarage",
          "freeStreet",
          "paidLotGarage",
          "paidStreet",
          "bikeRack",
          "loadingBay",
        ],
        secondaryInputMap: {
          freeLotGarage: [
            "freeLotGarageAccessibleParking",
            "freeLotGarageHours",
          ],
          freeStreet: ["freeStreetAccessibleParking", "freeStreetHours"],
          paidLotGarage: [
            "paidLotGarageAccessibleParking",
            "paidLotGarageHours",
            "paidLotGaragePrices",
          ],
          paidStreet: [
            "paidStreetAccessibleParking",
            "paidStreetHours",
            "paidStreetPrices",
          ],
          bikeRack: [],
          loadingBay: [],
        },
      },
      inputs: [
        {
          id: Date.now() + 81,
          label: "Free Lot or Garage",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeLotGarage",
          secondaryFor: null,
        },
        {
          id: Date.now() + 82,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeLotGarageAccessibleParking",
          secondaryFor: "freeLotGarage",
        },
        {
          id: Date.now() + 83,
          label: "Free Lot or Garage Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "freeLotGarageHours",
          secondaryFor: "freeLotGarage",
        },
        {
          id: Date.now() + 84,
          label: "Free Street",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeStreet",
          secondaryFor: null,
        },
        {
          id: Date.now() + 85,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeStreetAccessibleParking",
          secondaryFor: "freeStreet",
        },
        {
          id: Date.now() + 86,
          label: "Free Street Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "freeStreetHours",
          secondaryFor: "freeStreet",
        },
        {
          id: Date.now() + 87,
          label: "Paid Lot or Garage",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidLotGarage",
          secondaryFor: null,
        },
        {
          id: Date.now() + 88,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidLotGarageAccessibleParking",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 89,
          label: "Paid Lot or Garage Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "paidLotGarageHours",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 90,
          label: "Paid Lot or Garage Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "2000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: ["Parking"],
          customCategoryOptions: [],
          priceModeOptions: [
            "Free",
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            Parking: ["Per Hour", "Per Day", "One-time"],
          },
          customUnitOptionsByCategory: {},
          inputKey: "paidLotGaragePrices",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 91,
          label: "Paid Street",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidStreet",
          secondaryFor: null,
        },
        {
          id: Date.now() + 92,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidStreetAccessibleParking",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 93,
          label: "Paid Street Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "paidStreetHours",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 94,
          label: "Paid Street Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "2000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: ["Parking"],
          customCategoryOptions: [],
          priceModeOptions: [
            "Free",
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            Parking: ["Per Hour", "Per Day", "One-time"],
          },
          customUnitOptionsByCategory: {},
          inputKey: "paidStreetPrices",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 95,
          label: "Bike Rack",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "bikeRack",
          secondaryFor: null,
        },
        {
          id: Date.now() + 96,
          label: "Loading Bay",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "loadingBay",
          secondaryFor: null,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Ages
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 100,
      name: "Ages",
      systemKey: "ages",
      inputs: [
        {
          id: Date.now() + 101,
          label: "Age Range",
          type: "ageRange",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 150,
          ageModeOptions: ["All Ages", "Min-Max Range", "Min Only", "Max Only"],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Temperature & Air Control
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 110,
      name: "Temperature & Air Control",
      inputs: [
        {
          id: Date.now() + 111,
          label: "Warming Centre",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 112,
          label: "Cooling Centre",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 113,
          label: "Clean Air Space",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Food & Water
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 120,
      name: "Food & Water",
      inputs: [
        {
          id: Date.now() + 121,
          label: "Drinking Water",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 122,
          label: "Meals",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 123,
          label: "Community Fridge",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 124,
          label: "Food Bank",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Washrooms & Hygiene
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 130,
      name: "Washrooms & Hygiene",
      inputs: [
        {
          id: Date.now() + 131,
          label: "Washrooms",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 132,
          label: "Showers",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 133,
          label: "Hygiene Products",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Clothing & Laundry
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 140,
      name: "Clothing & Laundry",
      inputs: [
        {
          id: Date.now() + 141,
          label: "Clothing",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 142,
          label: "Laundry",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Rest & Seating
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 150,
      name: "Rest & Seating",
      inputs: [
        {
          id: Date.now() + 151,
          label: "Rest Area",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 152,
          label: "Seating Area",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Technology
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 160,
      name: "Technology",
      inputs: [
        {
          id: Date.now() + 161,
          label: "Computer Access",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 162,
          label: "Wi-Fi",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 163,
          label: "Charging Stations",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 164,
          label: "Phone Access",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
        {
          id: Date.now() + 165,
          label: "Printer Access",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Storage
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 170,
      name: "Storage",
      inputs: [
        {
          id: Date.now() + 171,
          label: "Storage",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
        },
      ],
    },

 // ─────────────────────────────────────────────
// Accessibility Features
// ─────────────────────────────────────────────
{
  id: Date.now() + 180,
  name: "Accessibility Features",
  inputs: [
    {
      id: Date.now() + 181,
      label: "Accessibility Features",
      type: "tagList",
      isRequired: false,
      isFilter: true,
      isDisplayed: true,
      displayIfEmpty: false,
      emptyDisplayText: "",
      maxLength: 150,
      maxItems: 1000,
      allowCustomTags: true,
      customTags: [],
      defaultTags: [
        // General / catch-all
        "Accessible Entrance",
        "Accessible Washroom",
        "Accessible Parking",
        "Barrier-Free Path of Travel",
        "Step-Free Access",

        // Mobility / physical access
        "Ramp",
        "Curb Cut",
        "Wide Doorways",
        "Automatic Doors",
        "Elevator",
        "Accessible Seating",
        "Wheelchair Accessible Tables",
        "Accessible Counter Height",
        "Smooth or Firm Ground Surface",
        "Accessible Route From Parking",
        "Accessible Drop-Off Area",

        // Washroom details
        "Gender Neutral Washroom",
        "Family Washroom",
        "Changing Table",
        "Adult Change Table",
        "Automatic Washroom Door",
        "Accessible Washroom Stalls",
        "Washroom Handrails",
        "Accessible Sink",
        "Automatic Faucet",
        "Low-Height Mirror",
        "Emergency Call Button",

        // Vision access
        "Braille Signage",
        "Tactile Signage",
        "High Contrast Signage",
        "Large Print Materials",
        "Good Lighting",
        "Tactile Ground Surface Indicators",
        "Audio Description Available",

        // Hearing access
        "Assistive Listening System",
        "Hearing Loop",
        "Captioning Available",
        "Live Captions Available",
        "Sign Language Interpretation Available",
        "Visual Alerts",

        // Cognitive / sensory access
        "Quiet Area",
        "Low Sensory Space",
        "Low Lighting Option",
        "Reduced Noise Area",
        "Clear Wayfinding",
        "Simple Signage",
        "Sensory-Friendly Hours",
        "Crowd-Free Hours",

        // Service / policy / support
        "Service Animals Welcome",
        "Support Person Welcome",
        "Staff Assistance Available",
        "Accessibility Information Available Online",
        "Accessible Booking Process",
        "Accessible Public Transit Nearby",

        // Language access / communication
        "Multilingual Staff",
        "Translation Support Available",
        "Interpretation Available",
        "Phone Interpretation Available",
        "Video Interpretation Available",
        "ASL Interpretation Available",
        "LSQ Interpretation Available",
        "Plain Language Information",
        "Multilingual Signage",
        "Multilingual Materials",
        "Language Access Information Available Online",
      ],
    },
  ],
},

    // ─────────────────────────────────────────────
    // Notes
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 190,
      name: "Notes",
      inputs: [
        {
          id: Date.now() + 191,
          label: "Notes",
          type: "notes",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 1000,
        },
      ],
    },
  ],

  extensions: {
    Gallery: {
      enabled: true,
      perDataItemToggle: true,
      maxImages: 10,
    },
    Guestbook: {
      enabled: false,
      perDataItemToggle: false,
    },
    Bulletin: {
      enabled: true,
      maxMessages: 20,
      messageLength: 1000,
    },
    Chat: {
      enabled: false,
      maxMessages: 0,
      messageLength: 0,
    },
  },
};
