// server/engines/neighbourhoods/schema.js

export const defaultNeighbourhoodSchema = {
  engineKey: "neighbourhoods",
  projectName: "Neighbourhood Services",
  projectDescription: "",
  projectTags: [],
  ownerColorTheme: "green",
  previewText:
    "sections[0].inputs[0].value sections[0].inputs[1].label sections[0].inputs[1].value",
  geometry: {
    label: "Geometry",
    types: ["Polygon"],
    isFilter: true,
    isDisplayed: false,
  },

  time: {
    label: "Timezone",
    type: "None",
    isFilter: false,
    isDisplayed: false,
  },

  sections: [
    {
      id: Date.now() + 10,
      name: "Location",
      inputs: [
        {
          id: Date.now() + 11,
          label: "Neighbourhood",
          type: "text",
          isRequired: true,
          isFilter: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
        {
          id: Date.now() + 12,
          label: "Population",
          type: "number",
          isRequired: true,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 7,
          minValue: 0,
          maxValue: 9999999,
          modeOptions: ["Single Value"],
        },
      ],
    },

    {
      id: Date.now() + 15,
      name: "Census Base Metrics",
      inputs: [
        {
          id: Date.now() + 16,
          label: "Municipality",
          type: "text",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 100,
        },
        {
          id: Date.now() + 17,
          label: "Total Private Dwellings",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 7,
          minValue: 0,
          maxValue: 9999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 18,
          label: "Occupied Private Dwellings",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 7,
          minValue: 0,
          maxValue: 9999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 19,
          label: "Land Area (sq km)",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 12,
          minValue: 0,
          maxValue: 9999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 20,
          label: "Population Density (per sq km)",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 12,
          minValue: 0,
          maxValue: 9999999,
          modeOptions: ["Single Value"],
        },
      ],
    },

    {
      id: Date.now() + 20,
      name: "Neighbourhood Assets",
      inputs: [
        {
          id: Date.now() + 21,
          label: "Green Space",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 4,
          minValue: 0,
          maxValue: 9999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 22,
          label: "Schools",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 4,
          minValue: 0,
          maxValue: 9999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 23,
          label: "Libraries",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 4,
          minValue: 0,
          maxValue: 9999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 24,
          label: "Healthcare",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 4,
          minValue: 0,
          maxValue: 9999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 25,
          label: "Transit Stops",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 4,
          minValue: 0,
          maxValue: 9999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 26,
          label: "Community Spaces",
          type: "number",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 4,
          minValue: 0,
          maxValue: 9999,
          modeOptions: ["Single Value"],
        },
      ],
    },

    {
      id: Date.now() + 30,
      name: "Neighbourhood Capacity",
      inputs: [
        {
          id: Date.now() + 31,
          label: "Green Space Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 32,
          label: "School Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 33,
          label: "Library Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 34,
          label: "Healthcare Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 35,
          label: "Transit Stop Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 36,
          label: "Community Space Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value"],
        },
      ],
    },

    {
      id: Date.now() + 40,
      name: "Neighbourhood Profile (%)",
      inputs: [
        {
          id: Date.now() + 41,
          label: "Single-Detached Housing",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 42,
          label: "Overcrowded Housing",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 43,
          label: "Unaffordable Housing",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 44,
          label: "Transit Commuters",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 45,
          label: "Households with Children",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 46,
          label: "Low-Income Households",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 47,
          label: "Non-Official Language Speakers",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
        {
          id: Date.now() + 48,
          label: "Visible Minorities",
          type: "percentage",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 100,
          modeOptions: ["Single Value"],
        },
      ],
    },
  ],

  extensions: {
    Bulletin: {
      enabled: true,
      maxMessages: 20,
      messageLength: 1000,
    },
    Chat: {
      enabled: false,
      maxMessages: 0,
      messageLength: 0,
    },
  },
};
