export const ParkingSection = {
  key: "parking",
  label: "Parking",

  buildSection() {
    return {
      id: Date.now() + 10,
      name: "Parking",
      systemKey: "parking",
      conditionalSection: "checkboxGate",

      checkboxGateConfig: {
        primaryInputKeys: [
          "freeLotGarage",
          "freeStreet",
          "paidLotGarage",
          "paidStreet",
          "bikeRack",
          "loadingBay",
        ],

        secondaryInputMap: {
          freeLotGarage: [
            "freeLotGarageAccessibleParking",
            "freeLotGarageHours",
          ],
          freeStreet: ["freeStreetAccessibleParking", "freeStreetHours"],
          paidLotGarage: [
            "paidLotGarageAccessibleParking",
            "paidLotGarageHours",
            "paidLotGaragePrices",
          ],
          paidStreet: [
            "paidStreetAccessibleParking",
            "paidStreetHours",
            "paidStreetPrices",
          ],
          bikeRack: [],
          loadingBay: [],
        },
      },

      inputs: [
        {
          id: Date.now() + 11,
          label: "Free Lot or Garage",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeLotGarage",
          secondaryFor: null,
        },
        {
          id: Date.now() + 12,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeLotGarageAccessibleParking",
          secondaryFor: "freeLotGarage",
        },
        {
          id: Date.now() + 13,
          label: "Free Lot or Garage Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "freeLotGarageHours",
          secondaryFor: "freeLotGarage",
        },

        {
          id: Date.now() + 14,
          label: "Free Street",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeStreet",
          secondaryFor: null,
        },
        {
          id: Date.now() + 15,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeStreetAccessibleParking",
          secondaryFor: "freeStreet",
        },
        {
          id: Date.now() + 16,
          label: "Free Street Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "freeStreetHours",
          secondaryFor: "freeStreet",
        },

        {
          id: Date.now() + 17,
          label: "Paid Lot or Garage",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidLotGarage",
          secondaryFor: null,
        },
        {
          id: Date.now() + 18,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidLotGarageAccessibleParking",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 19,
          label: "Paid Lot or Garage Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "paidLotGarageHours",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 20,
          label: "Paid Lot or Garage Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "2000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: ["Parking"],
          customCategoryOptions: [],
          priceModeOptions: [
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            Parking: ["Per Hour", "Per Day", "One-time"],
          },
          customUnitOptionsByCategory: {},
          inputKey: "paidLotGaragePrices",
          secondaryFor: "paidLotGarage",
        },

        {
          id: Date.now() + 21,
          label: "Paid Street",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          notes: "",
          isApplicableOption: false,
          inputKey: "paidStreet",
          secondaryFor: null,
        },
        {
          id: Date.now() + 22,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidStreetAccessibleParking",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 23,
          label: "Paid Street Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "paidStreetHours",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 24,
          label: "Paid Street Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "2000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: ["Parking"],
          customCategoryOptions: [],
          priceModeOptions: [
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            Parking: ["Per Hour", "Per Day", "One-time"],
          },
          customUnitOptionsByCategory: {},
          inputKey: "paidStreetPrices",
          secondaryFor: "paidStreet",
        },

        {
          id: Date.now() + 25,
          label: "Bike Rack",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "bikeRack",
          secondaryFor: null,
        },
        {
          id: Date.now() + 26,
          label: "Loading Bay",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "loadingBay",
          secondaryFor: null,
        },
      ],
    };
  },

  schemaRules: {
    lockedSectionFields: [
      "systemKey",
      "conditionalSection",
      "checkboxGateConfig",
    ],
    lockedInputs: [
      {
        inputIndex: 0,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 1,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 2,
        lockedFields: ["label", "type", "inputKey", "secondaryFor"],
      },

      {
        inputIndex: 3,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 4,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 5,
        lockedFields: ["label", "type", "inputKey", "secondaryFor"],
      },

      {
        inputIndex: 6,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 7,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 8,
        lockedFields: ["label", "type", "inputKey", "secondaryFor"],
      },
      {
        inputIndex: 9,
        lockedFields: [
          "label",
          "type",
          "minValue",
          "maxValue",
          "maxLength",
          "maxTotalPriceItems",
          "maxItemsPerCategory",
          "maxCategories",
          "maxUnitsPerCategory",
          "allowCustomCategoriesAndUnits",
          "defaultCategoryOptions",
          "priceModeOptions",
          "inputKey",
          "secondaryFor",
        ],
      },

      {
        inputIndex: 10,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 11,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 12,
        lockedFields: ["label", "type", "inputKey", "secondaryFor"],
      },
      {
        inputIndex: 13,
        lockedFields: [
          "label",
          "type",
          "minValue",
          "maxValue",
          "maxLength",
          "maxTotalPriceItems",
          "maxItemsPerCategory",
          "maxCategories",
          "maxUnitsPerCategory",
          "allowCustomCategoriesAndUnits",
          "defaultCategoryOptions",
          "priceModeOptions",
          "inputKey",
          "secondaryFor",
        ],
      },

      {
        inputIndex: 14,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
      {
        inputIndex: 15,
        lockedFields: [
          "label",
          "type",
          "displayWhenTrue",
          "displayWhenFalse",
          "trueDisplayText",
          "falseDisplayText",
          "isApplicableOption",
          "notes",
          "inputKey",
          "secondaryFor",
        ],
      },
    ],
  },
};
