export const PhysicalBarriersSection = {
  key: "physicalBarriers",
  label: "Physical Barriers",

  buildSection() {
    return {
      id: Date.now() + 10,
      name: "Physical Barriers",
      systemKey: "physicalBarriers",
      inputs: [
        {
          id: Date.now() + 11,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Accessible Parking",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 12,
          label: "Ramp",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Ramp",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 13,
          label: "Automatic Doors",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Automatic Doors",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 14,
          label: "Elevator",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Elevator",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 15,
          label: "Accessible Seating",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Accessible Seating",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 16,
          label: "Automatic Washroom Door",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Automatic Washroom Door",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 17,
          label: "Accessible Sink",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Accessible Sink",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 18,
          label: "Automatic Faucet",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Automatic Faucet",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 19,
          label: "Washroom Handrails",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Washroom Handrails",
          isApplicableOption: true,
          notes: "",
        },
        {
          id: Date.now() + 20,
          label: "Accessible Washroom Stalls",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "none",
          displayWhenFalse: "messageOnly",
          trueDisplayText: "",
          falseDisplayText: "No Accessible Washroom Stalls",
          isApplicableOption: true,
          notes: "",
        },
      ],
    };
  },

  schemaRules: {
    lockedSectionFields: ["name", "systemKey"],
    lockedInputs: [
      { inputIndex: 0, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 1, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 2, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 3, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 4, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 5, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 6, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 7, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 8, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
      { inputIndex: 9, lockedFields: ["label", "type", "isFilter", "displayWhenTrue", "displayWhenFalse", "trueDisplayText", "falseDisplayText", "isApplicableOption", "notes"] },
    ],
  },
};