// server/engines/events/schema.js

export const defaultEventSchema = {
  engineKey: "events",
  projectName: "City Events",
  projectDescription: "",
  projectTags: [],
  ownerColorTheme: "green",
  previewText: "sections[0].inputs[0].value",

  geometry: {
    label: "Geometry",
    types: ["Point", "LineString", "Polygon"],
    isFilter: true,
    isDisplayed: true,
  },

  time: {
    label: "Date & Time",
    type: "Event",
    isFilter: true,
    isDisplayed: true,
    defaultDurationMinutes: 120,
    modes: ["Range", "Instant", "Ongoing"],
  },

  sections: [
    // ─────────────────────────────────────────────
    // Location
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 10,
      name: "Location",
      systemKey: "location",
      inputs: [
        {
          id: Date.now() + 11,
          label: "Event Name",
          type: "text",
          isRequired: true,
          isFilter: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
        {
          id: Date.now() + 12,
          label: "Address",
          type: "text",
          isRequired: false,
          isFilter: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Details
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 20,
      name: "Details",
      inputs: [
        {
          id: Date.now() + 21,
          label: "Description",
          type: "notes",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 1000,
        },
        {
          id: Date.now() + 22,
          label: "Category",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: [
            "Seasonal / Holiday",
            "Arts / Culture / Entertainment",
            "Food & Drink",
            "Community & Social",
            "Sports & Recreation",
            "Education & Work",
            "Lectures & Talks",
            "Workshops & Programs",
            "Family & Youth",
            "Mentorship & Leadership",
            "Civic & Public",
            "Markets & Shopping",
            "Nature",
            "Nightlife",
            "Special Interest",
            "Other",
          ],
        },
        {
          id: Date.now() + 23,
          label: "Registration",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: ["Not Required", "Optional", "Required"],
        },
        {
          id: Date.now() + 24,
          label: "Website",
          type: "website",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
        {
          id: Date.now() + 25,
          label: "Registration Link",
          type: "website",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Contact Details
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 30,
      name: "Contact Details",
      systemKey: "contact",
      inputs: [
        {
          id: Date.now() + 31,
          label: "Website",
          type: "website",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
        {
          id: Date.now() + 32,
          label: "Phone",
          type: "phoneNumber",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 25,
        },
        {
          id: Date.now() + 33,
          label: "Extension",
          type: "text",
          isRequired: false,
          isFilter: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 20,
        },
        {
          id: Date.now() + 34,
          label: "Email",
          type: "email",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Capacity
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 40,
      name: "Capacity",
      systemKey: "capacity",
      inputs: [
        {
          id: Date.now() + 41,
          label: "Capacity",
          type: "capacity",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 9,
          minValue: 0,
          maxValue: 999999999,
          modeOptions: ["Single Value", "Min-Max Range"],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Access Conditions
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 50,
      name: "Access Conditions",
      inputs: [
        {
          id: Date.now() + 51,
          label: "Indoor/Outdoor",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: ["Indoor", "Outdoor", "Both"],
        },
        {
          id: Date.now() + 52,
          label: "Noise Level",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: ["Low", "Medium", "High"],
        },
        {
          id: Date.now() + 53,
          label: "Pet Friendly",
          type: "dropdown",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          options: ["Pets Allowed", "Service Animals Only", "No Pets Allowed"],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Financial Access
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 60,
      name: "Financial Access",
      systemKey: "financialAccess",
      inputs: [
        {
          id: Date.now() + 61,
          label: "Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "100000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: [
            "Entry Fee",
            "Rental Fee",
            "Ticket",
            "Donation",
            "Item",
            "Service",
            "Food",
            "Merch",
            "Exercise Class",
            "Photography",
            "Membership",
          ],
          customCategoryOptions: [],
          priceModeOptions: [
            "Free",
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            "Entry Fee": ["One-time", "Per Person", "Per Group"],
            "Rental Fee": ["One-time", "Per Person", "Per Group", "Per Hour"],
            Ticket: ["Per Person", "Per Group"],
            Donation: ["One-time", "Per Person"],
            Item: ["Per Item"],
            Service: ["Per Hour", "Per Session", "One-time"],
            Food: ["Per Item"],
            Merch: ["Per Item"],
            "Exercise Class": ["Per Class"],
            Photography: ["Per Session", "Per Hour"],
            Membership: ["Per Month", "Per Year"],
          },
          customUnitOptionsByCategory: {},
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Parking
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 70,
      name: "Parking",
      systemKey: "parking",
      conditionalSection: "checkboxGate",
      checkboxGateConfig: {
        primaryInputKeys: [
          "freeLotGarage",
          "freeStreet",
          "paidLotGarage",
          "paidStreet",
          "bikeRack",
          "loadingBay",
        ],
        secondaryInputMap: {
          freeLotGarage: [
            "freeLotGarageAccessibleParking",
            "freeLotGarageHours",
          ],
          freeStreet: ["freeStreetAccessibleParking", "freeStreetHours"],
          paidLotGarage: [
            "paidLotGarageAccessibleParking",
            "paidLotGarageHours",
            "paidLotGaragePrices",
          ],
          paidStreet: [
            "paidStreetAccessibleParking",
            "paidStreetHours",
            "paidStreetPrices",
          ],
          bikeRack: [],
          loadingBay: [],
        },
      },
      inputs: [
        {
          id: Date.now() + 71,
          label: "Free Lot or Garage",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeLotGarage",
          secondaryFor: null,
        },
        {
          id: Date.now() + 72,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeLotGarageAccessibleParking",
          secondaryFor: "freeLotGarage",
        },
        {
          id: Date.now() + 73,
          label: "Free Lot or Garage Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "freeLotGarageHours",
          secondaryFor: "freeLotGarage",
        },
        {
          id: Date.now() + 74,
          label: "Free Street",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeStreet",
          secondaryFor: null,
        },
        {
          id: Date.now() + 75,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "freeStreetAccessibleParking",
          secondaryFor: "freeStreet",
        },
        {
          id: Date.now() + 76,
          label: "Free Street Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "freeStreetHours",
          secondaryFor: "freeStreet",
        },
        {
          id: Date.now() + 77,
          label: "Paid Lot or Garage",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidLotGarage",
          secondaryFor: null,
        },
        {
          id: Date.now() + 78,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidLotGarageAccessibleParking",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 79,
          label: "Paid Lot or Garage Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "paidLotGarageHours",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 80,
          label: "Paid Lot or Garage Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "2000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: ["Parking"],
          customCategoryOptions: [],
          priceModeOptions: [
            "Free",
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            Parking: ["Per Hour", "Per Day", "One-time"],
          },
          customUnitOptionsByCategory: {},
          inputKey: "paidLotGaragePrices",
          secondaryFor: "paidLotGarage",
        },
        {
          id: Date.now() + 81,
          label: "Paid Street",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidStreet",
          secondaryFor: null,
        },
        {
          id: Date.now() + 82,
          label: "Accessible Parking",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "paidStreetAccessibleParking",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 83,
          label: "Paid Street Hours",
          type: "hours",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          inputKey: "paidStreetHours",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 84,
          label: "Paid Street Prices",
          type: "priceRangeArray",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 30,
          minValue: "0.00",
          maxValue: "2000.00",
          maxTotalPriceItems: 1000,
          maxItemsPerCategory: 50,
          maxCategories: 20,
          maxUnitsPerCategory: 10,
          allowCustomCategoriesAndUnits: true,
          defaultCategoryOptions: ["Parking"],
          customCategoryOptions: [],
          priceModeOptions: [
            "Free",
            "Fixed Price",
            "Min-Max Range",
            "Min Only",
            "Max Only",
          ],
          defaultPriceUnitOptionsByCategory: {
            Parking: ["Per Hour", "Per Day", "One-time"],
          },
          customUnitOptionsByCategory: {},
          inputKey: "paidStreetPrices",
          secondaryFor: "paidStreet",
        },
        {
          id: Date.now() + 85,
          label: "Bike Rack",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "bikeRack",
          secondaryFor: null,
        },
        {
          id: Date.now() + 86,
          label: "Loading Bay",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "",
          inputKey: "loadingBay",
          secondaryFor: null,
        },
      ],
    },
    // ─────────────────────────────────────────────
    // Ages
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 90,
      name: "Ages",
      systemKey: "ages",
      inputs: [
        {
          id: Date.now() + 91,
          label: "Age Range",
          type: "ageRange",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 3,
          minValue: 0,
          maxValue: 150,
          ageModeOptions: ["All Ages", "Min-Max Range", "Min Only", "Max Only"],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Features
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 100,
      name: "Features",
      inputs: [
        {
          id: Date.now() + 101,
          label: "Live Music",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Has live music.",
        },
        {
          id: Date.now() + 102,
          label: "Food",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Food vendors or food onsite.",
        },
        {
          id: Date.now() + 103,
          label: "Drinks",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Non-alcohol drinks onsite.",
        },
        {
          id: Date.now() + 104,
          label: "Vendors",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Vendor booths or marketplace.",
        },
        {
          id: Date.now() + 105,
          label: "Performers",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Shows/acts/performers.",
        },
        {
          id: Date.now() + 106,
          label: "Games",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Games or activities onsite.",
        },
        {
          id: Date.now() + 107,
          label: "Rides",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Rides (fair/carnival).",
        },
        {
          id: Date.now() + 108,
          label: "Kids Activities",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Kid-focused activities.",
        },
        {
          id: Date.now() + 109,
          label: "Alcohol",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Alcohol for purchase.",
        },
        {
          id: Date.now() + 110,
          label: "Workshops",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Hands-on workshops or guided sessions.",
        },
        {
          id: Date.now() + 111,
          label: "Programs",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Multi-session or ongoing programs.",
        },
        {
          id: Date.now() + 112,
          label: "Mentorship",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Mentorship, coaching, or leadership guidance.",
        },
        {
          id: Date.now() + 113,
          label: "Face Painting",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Face painting or similar kid-focused activities.",
        },
        {
          id: Date.now() + 114,
          label: "Comedians",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Stand-up comedy or comedic performances.",
        },
        {
          id: Date.now() + 115,
          label: "Swimming",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Swimming activities or water-based recreation.",
        },
        {
          id: Date.now() + 116,
          label: "Camping",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Camping or overnight outdoor activities.",
        },
        {
          id: Date.now() + 117,
          label: "Animals",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Animals present or animal-focused activities.",
        },
        {
          id: Date.now() + 118,
          label: "Sports",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "General sports or athletic activities.",
        },
        {
          id: Date.now() + 119,
          label: "Hobbies",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Hobby-based or interest-driven activities.",
        },
        {
          id: Date.now() + 120,
          label: "Crafts",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Arts, crafts, or hands-on creative activities.",
        },
        {
          id: Date.now() + 121,
          label: "Classes",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Instructors teaching a skill or offering guidance.",
        },
        {
          id: Date.now() + 122,
          label: "Art Exhibit",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Art such as painting, or sculptures on display",
        },
        {
          id: Date.now() + 123,
          label: "Film Screening",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "In person film screening.",
        },
        {
          id: Date.now() + 124,
          label: "Play",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Live performance of a play.",
        },
        {
          id: Date.now() + 125,
          label: "Author Showcase",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Author showcase, book signing, or book selling.",
        },
        {
          id: Date.now() + 126,
          label: "Other Activity",
          type: "checkbox",
          isFilter: true,
          displayWhenTrue: "labelOnly",
          displayWhenFalse: "none",
          trueDisplayText: "",
          falseDisplayText: "",
          isApplicableOption: false,
          notes: "Other notable activities not listed.",
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Accessibility Features
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 130,
      name: "Accessibility Features",
      inputs: [
        {
          id: Date.now() + 131,
          label: "Accessibility Features",
          type: "tagList",
          isRequired: false,
          isFilter: true,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 150,
          maxItems: 1000,
          allowCustomTags: true,
          customTags: [],
          defaultTags: [
            // General / catch-all
            "Accessible Entrance",
            "Accessible Washroom",
            "Accessible Parking",
            "Barrier-Free Path of Travel",
            "Step-Free Access",

            // Mobility / physical access
            "Ramp",
            "Curb Cut",
            "Wide Doorways",
            "Automatic Doors",
            "Elevator",
            "Accessible Seating",
            "Wheelchair Accessible Tables",
            "Accessible Counter Height",
            "Smooth or Firm Ground Surface",
            "Accessible Route From Parking",
            "Accessible Drop-Off Area",

            // Washroom details
            "Gender Neutral Washroom",
            "Family Washroom",
            "Changing Table",
            "Adult Change Table",
            "Automatic Washroom Door",
            "Accessible Washroom Stalls",
            "Washroom Handrails",
            "Accessible Sink",
            "Automatic Faucet",
            "Low-Height Mirror",
            "Emergency Call Button",

            // Vision access
            "Braille Signage",
            "Tactile Signage",
            "High Contrast Signage",
            "Large Print Materials",
            "Good Lighting",
            "Tactile Ground Surface Indicators",
            "Audio Description Available",

            // Hearing access
            "Assistive Listening System",
            "Hearing Loop",
            "Captioning Available",
            "Live Captions Available",
            "Sign Language Interpretation Available",
            "Visual Alerts",

            // Cognitive / sensory access
            "Quiet Area",
            "Low Sensory Space",
            "Low Lighting Option",
            "Reduced Noise Area",
            "Clear Wayfinding",
            "Simple Signage",
            "Sensory-Friendly Hours",
            "Crowd-Free Hours",

            // Service / policy / support
            "Service Animals Welcome",
            "Support Person Welcome",
            "Staff Assistance Available",
            "Accessibility Information Available Online",
            "Accessible Booking Process",
            "Accessible Public Transit Nearby",

            // Language access / communication
            "Multilingual Staff",
            "Translation Support Available",
            "Interpretation Available",
            "Phone Interpretation Available",
            "Video Interpretation Available",
            "ASL Interpretation Available",
            "LSQ Interpretation Available",
            "Plain Language Information",
            "Multilingual Signage",
            "Multilingual Materials",
            "Language Access Information Available Online",
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // Notes
    // ─────────────────────────────────────────────
    {
      id: Date.now() + 140,
      name: "Notes",
      inputs: [
        {
          id: Date.now() + 141,
          label: "Notes",
          type: "notes",
          isRequired: false,
          isDisplayed: true,
          displayIfEmpty: false,
          emptyDisplayText: "",
          maxLength: 1000,
        },
      ],
    },
  ],

  extensions: {
    Gallery: {
      enabled: true,
      perDataItemToggle: true,
      maxImages: 10,
    },
    Guestbook: {
      enabled: true,
      perDataItemToggle: true,
    },
    Bulletin: {
      enabled: true,
      maxMessages: 20,
      messageLength: 1000,
    },
    Chat: {
      enabled: false,
      maxMessages: 0,
      messageLength: 0,
    },
  },
};
